#!/bin/bash

APP_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
RESOURCES="$APP_DIR/Contents/Resources"
TARGET="/Applications"
SOURCE="$RESOURCES/Bibletool.app"
USER_NAME="$(stat -f "%Su" /dev/console)"

osascript <<EOF
do shell script "
  rm -rf '$TARGET/Bibletool.app' &&
  cp -R '$SOURCE' '$TARGET' &&
  chown -R '$USER_NAME':admin '$TARGET/Bibletool.app' &&
  sudo xattr -rd com.apple.quarantine '$TARGET/Bibletool.app'
" with administrator privileges
EOF

# Launch the app
open "$TARGET/Bibletool.app"